### ISSUE TITLE
Add your story formatting

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#102]
![image](https://cloud.githubusercontent.com/assets/1741923/23669491/3546fc50-0319-11e7-8eb4-125cea16ccf1.png)
I'm thinking these may not stand-out. I think a simple: "What's your border story?" on a red, green, or purple background will distinguish the call to action from other bordr stories. Also, it seems these only repeat once.

**Comment by andycarnahan** [comment]
I think you're right about needing to stand out more. Something is wrong if it only repeats once.

**Comment by jcdk** [comment]
![image](https://cloud.githubusercontent.com/assets/1741923/23775091/be5e38c8-04db-11e7-9282-5cdca8b56c91.png)
@haraldssonfoto formatting recommendation
