### ISSUE TITLE
hub partnerships render incorrectly

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#19]
The “Are you partnering with other hubs?” field (in the Hubs input page) mostly does not produce portfolio items on the Hubs pages. For example this one (affiliated with the most Activities) should now have been “involved” in 21 Activities…
It seems to have gotten worse after the server update (is there a general thing to check? I have now given all project the correct affiliations, but they don´t render correctly…

**Comment by haraldssonfoto** [comment]
This issue is still around, no change what I´ve seen. http://globalgrandcentral.net/author/EuropeGrandCentral/ should show 21 projects, but shows only 5

**Comment by jcdk** [comment]
does [the EGC partnership involvement page](http://globalgrandcentral.net/author/EuropeGrandCentral/) look correct now?

**Comment by haraldssonfoto** [comment]
Indeed!! All the Activities are there! 
(however the cards render funny, with lots of space between)

**Comment by jcdk** [comment]
Are you sure? Try shift+refresh to update everything on the page.

**Comment by haraldssonfoto** [comment]
Yep! Thanks, thats much better - perfect actually!
