### ISSUE TITLE
Transactional email address setup

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#30]

**Comment by jcdk** [comment]
Which email addresse(s) should we setup? @haraldssonfoto would you want a GlobalGrandCentral-branded email account hosted through Google (it will look like a Gmail account, but with GGC branding)?  At minimum I'll add:
contact@globalgrandcentral.net

- Christo

**Comment by haraldssonfoto** [comment]
Hey!

I just managed to get my marcus@bordr.org working...

But, sure, let's do a marcus@globalgrandcentral.net as well (as long as it
can link to my regular gmail) or is there a drawback? Are you doing Bordr
or globalgrandcentral, or both?

Then. From what address will account info (setup, password, etc) be sent?
And is that a no-reply address?

And is there a good easy setup to gather all users (and interested) for
messages info, technical updates, and newsletters (with opt-out option)?

It's a bit of setup.. (and I understand why it's better to do it all now!!)

M



tis 27 dec. 2016 kl. 13:47 skrev Christo de Klerk <notifications@github.com

**Comment by jcdk** [comment]
@haraldssonfoto for the sake of reliability, cost, and limiting the number of email accounts, I've changed my mind and think the best route is to have emails sent from the server via a SendGrid email relay service ($10 to $20/mth) using the email address contact@globalgrandcentral.net and then have any emails that are sent to that address forwarded to an existing address like hello@bordr.org 

Regarding:
> And is there a good easy setup to gather all users (and interested) for messages info, technical updates, and newsletters (with opt-out option)?

Sendgrid will work well for this as it has all these features and is a little cheaper than the Mailchimp account we were using.  A newsletter is called a "marketing campaign". I'll send you login credentials.
