### ISSUE TITLE
Activities detail: wrong Stories showing for activity

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#31]
Relating to [Activity](http://europegrandcentral.net/activity/921/) - this Activity lists (erroneously) the same Bordr Stories as [Activity](http://europegrandcentral.net/activity/interzona-outerzona/) @haraldssonfoto has tried to re-save the Stories but they still show up as part of Dinas results.

**Comment by haraldssonfoto** [comment]
This issue is still alive (wrong list of Bordrs) on http://www.globalgrandcentral.net/activity/921/

**Comment by jcdk** [comment]
Okay, check it out now, @haraldssonfoto 

Issue should now be fixed
