### ISSUE TITLE
Activity and Story page navigation / infinite scroll

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#63]
![image](https://cloud.githubusercontent.com/assets/1741923/22944239/e0a7526e-f2a4-11e6-9099-29fbf384e3cf.png)

This should be clearer, perhaps read "Load More" and maybe point down instead.

nuthemes_content_nav() function needs to be migrated to bordr theme from pieces theme to make the changes work, unless a new custom navigation function should be made.

Or should this be an endless scroll function like pinterest or facebook?

**Comment by andycarnahan** [comment]
Endless scroll would be ideal, I think? Otherwise, down arrow sounds good.

**Comment by jcdk** [comment]
Got jetpacks infinite scroll to work fairly quickly, but it doesn't appear to work correctly when a filter is applied.  Working on figuring that out.

**Comment by jcdk** [comment]
Stumped.  Shared the [issue on SO](http://wordpress.stackexchange.com/questions/256750/passing-meta-query-or-author-in-to-jetpack-infinite-scroll-query)
